### ISSUE TITLE
comparison of segmentation methods

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#12]
https://github.com/Mathilde-16/STOP_MS_data/blob/24e106b3ddfe728378e7a3854cacdec42fd345aa/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L66

to cleanup the code I suggest you document the difference between the two algos, pick the best one, and remove the code related to the other method

**Comment by Mathilde-16** [comment]
For me, I think the best one is the one which uses the **sct_deepseg** command (the contrast agnostic segmentation model), indeed the QC [here](https://github.com/Mathilde-16/STOP_MS_data/issues/2#issuecomment-2138237283) shows a better segmentation with this model than with the sct_deepseg_sc command.

So you agree if I remove the code related to the sct_deepseg_sc ?

**Comment by Mathilde-16** [comment]
Thanks for your approval, I've commited [the cleaned code](https://github.com/Mathilde-16/STOP_MS_data/blob/ff54c5ce67cde853f752fcba6dc1a9fa349cb055/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh)

**Comment by jcohenadad** [comment]
> Thanks for your approval, I've commited the cleaned code

please always cross-ref to the commit SHA next to your comment "I've commited the cleaned code" to avoid confusion (ie: the code is constantly evolving)

**Comment by Mathilde-16** [comment]
Yes of course sorry !

**Comment by jcohenadad** [comment]
please note that pointing to the [diff of the commit](https://github.com/Mathilde-16/STOP_MS_data/commit/ff54c5ce67cde853f752fcba6dc1a9fa349cb055) is more useful because it enables to see what differs from the previous version (easier to quickly assess the changes)

**Comment by jcohenadad** [comment]
Issue can be closed

**Comment by Mathilde-16** [comment]
> please note that pointing to the [diff of the commit](https://github.com/Mathilde-16/STOP_MS_data/commit/ff54c5ce67cde853f752fcba6dc1a9fa349cb055) is more useful because it enables to see what differs from the previous version (easier to quickly assess the changes)

Okay I understand, thank you !
