### ISSUE TITLE
why isn’t this applicable to sct_deepseg as well?

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#13]
https://github.com/Mathilde-16/STOP_MS_data/blob/24e106b3ddfe728378e7a3854cacdec42fd345aa/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L89-L93

Related to https://github.com/Mathilde-16/STOP_MS_data/issues/9

**Comment by Mathilde-16** [comment]
Sorry I got confused, I wanted to refer to the computation of CSA but I was wrong in my comments, they should have been "Not necessary if we only compute the CSA".

**Comment by jcohenadad** [comment]
Now fixed
