### ISSUE TITLE
`#!/bin/sh` is not needed at the top of a YAML file.

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#16]
version https://github.com/Mathilde-16/STOP_MS_data/commit/cddac703d6ac506f54c47222522efb79f47e08ac indicated: `#!/bin/sh` at the top of the YAML file.

However, `#!/bin/sh` is not needed at the top of a YAML file. The #!/bin/sh (shebang) line is used at the beginning of shell scripts to indicate which interpreter should be used to run the script. YAML files are configuration files and are not executable scripts, so they do not require a shebang line.

**Comment by Mathilde-16** [comment]
Okay, thank you for this explanation.
