### ISSUE TITLE
Flag a QC with "Fail" or "Pass" in order to set up the manual segmentation 

### ISSUE THREAD

**Issue by Mathilde-16** [Mathilde-16/STOP_MS_data#2]
Regarding the manual segmentation, I haven't done it yet because I would like to know, please, if you can help me find out how to determine whether segmentation worked or not when we look at the QC (in order to flag it with “Fail” or “Pass”) ? 

I guess isn't always easy to spot the issues and that it's very important to get this right and to make no mistakes. 

Thank you for your help !

**Comment by Mathilde-16** [comment]
Hi again, just a few additional details ! 

The contrast agnostic segmentation qc (index.html file) shows better results than the segmentation qc, as we could have expected. Indeed, output for the sct_deepseg_sc command looks like this for several people : 
[Screenshot.pdf](https://github.com/Mathilde-16/STOP_MS_data/files/15475843/Screenshot.pdf)


I tried to flag and complete both QC corresponding to the links below. I've probably made several mistakes but it was just a training exercise before your recommendations. 
- segmentation with sct_deepseg_sc, and labeling : [file:///Users/mathilde/Desktop/BIDS_DATASET_seg_copy_3_seg+label/sct_v6.3/sct_v6.3_segmentation/OUTPUT/qc/index.html](url)
- contrast agnostic segmentation, and labeling : [file:///Users/mathilde/Desktop/BIDS_DATASET_contrast-agnost-seg+label_copy_4/derivaties/sct_v6.3_contrast-agnostic/qc/index.html](url)

**Comment by jcohenadad** [comment]
> Regarding the manual segmentation, I haven't done it yet because I would like to know, please, if you can help me find out how to determine whether segmentation worked or not when we look at the QC (in order to flag it with “Fail” or “Pass”) ?

i suggest you go through a QC, flag pass/fail, and i can have a quick look to let you know if i agree with it

**Comment by Mathilde-16** [comment]
> I tried to flag and complete both QC corresponding to the links below. I've probably made several mistakes but it was just a training exercise before your recommendations.

> segmentation with sct_deepseg_sc, and labeling : [file:///Users/mathilde/Desktop/BIDS_DATASET_seg_copy_3_seg+label/sct_v6.3/sct_v6.3_segmentation/OUTPUT/qc/index.html](https://github.com/Mathilde-16/STOP_MS_data/issues/url)

> contrast agnostic segmentation, and labeling : [file:///Users/mathilde/Desktop/BIDS_DATASET_contrast-agnost-seg+label_copy_4/derivaties/sct_v6.3_contrast-agnostic/qc/index.html](https://github.com/Mathilde-16/STOP_MS_data/issues/url)

I think what I did above is what you mean, no ? If you copy and paste both links into a search engine, you should have access to the QCs I tried to evaluate ?

**Comment by jcohenadad** [comment]
no-- you pointed to a LOCAL URL https://askubuntu.com/questions/932215/make-url-point-to-local-folder

check your URL: it starts with "local"-- you need to downlaod, zip, upload here (or somewhere else on the cloud if too big)

**Comment by Mathilde-16** [comment]
Please find below both QC

- segmentation with sct_deepseg_sc, and labeling : 
[index.html.zip](https://github.com/Mathilde-16/STOP_MS_data/files/15490663/index.html.zip)

- contrast agnostic segmentation, and labeling : 
[index.html.zip](https://github.com/Mathilde-16/STOP_MS_data/files/15490671/index.html.zip)

**Comment by jcohenadad** [comment]
in https://github.com/Mathilde-16/STOP_MS_data/issues/2#issuecomment-2138237283 you only zipped the HTML file but not the images that the HTML code depends on-- you need to zip the entire QC folder--

**Comment by Mathilde-16** [comment]
My apologies.

Please find below both compressed QC folders,

- segmentation with sct_deepseg_sc, and labeling :
 [qc.zip](https://github.com/user-attachments/files/15506543/qc.zip)

- contrast agnostic segmentation, and labeling :
[qc.zip](https://github.com/user-attachments/files/15741124/qc.zip)

**Comment by jcohenadad** [comment]
> The contrast agnostic segmentation qc (index.html file) shows better results than the segmentation qc, as we could have expected

Agreed!

**Comment by jcohenadad** [comment]
we can consider this issue fixed-- closing
