### ISSUE TITLE
Consider using PMJ to bypass vertebral labeling

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#20]
Given the difficulty to perform reliable vertebral labeling #6, we could consider detecting the pontomedullary junction and then measuring CSA based on the distance from the PMJ, as suggested in https://www.frontiersin.org/journals/neuroimaging/articles/10.3389/fnimg.2022.1031253/full

**Comment by jcohenadad** [comment]
@Mathilde-16 please do not close the issues/PR I am working on. I've been processing the data, planning to document the results and discuss wether it should be merged or not.

**Comment by Mathilde-16** [comment]
Of course, my apologies ! And thank you for your help and your suggestion to use the PMJ in order to measure CSA.

**Comment by jcohenadad** [comment]
Fixed by #21 #26
