### ISSUE TITLE
Unclear repos structure and multiple version

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#3]
<img width="435" alt="image" src="https://github.com/Mathilde-16/STOP_MS_data/assets/2482071/3b7f2494-866f-4ea9-b67e-17dc62909bc6">

- The repos is currently difficult to understand-- there is data, there is code, and we don't know which is which
- this repos should not have data-- only code
- there are multiple versions of folders, which defeats the purpose of git-- git is a version tracking tool, you can create multiple branches with it, document them, cross-ref them in issues, etc. pls see git documentation/tutorials

**Comment by Mathilde-16** [comment]
I understand and I apologise. I've just deleted the data and I'm going to modify the repos organization to make it easier to understand.
My apologies again!
