### ISSUE TITLE
Data processing progress : segmentation and vertebral labeling

### ISSUE THREAD

**Issue by Mathilde-16** [Mathilde-16/STOP_MS_data#4]
Could you tell me what do you think about this script please ? 
[https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh](url)

**Comment by jcohenadad** [comment]
> Could you tell me what do you think about this script please ? [c5bbd51](https://github.com/Mathilde-16/STOP_MS_data/commit/c5bbd51d612161c7ff6d42657821202002fc3d41)

the link refers to a commit (with a LOT of changes), not a script. here is an example of a URL that points to a file at a specific commit SHA: https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/OUTPUT/Terminal_Output_batch_script

**Comment by Mathilde-16** [comment]
Thanks for the exemple, I've just edited my issues #4 and #5

**Comment by jcohenadad** [comment]
> Could you tell me what do you think about this script please ?
[https://github.com/Mathilde-16/STOP_MS_data/blob/main/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh](https://github.com/Mathilde-16/STOP_MS_data/issues/url)

no, this is pointing to the main branch (which is not static and always evolves with new commit)-- the 'main' should be replaced with the commit SHA of the script you would like feedback on

**Comment by Mathilde-16** [comment]
I've just edited issues #4 and #5 with the commit SHA

**Comment by jcohenadad** [comment]
this is the landing page for the URL you edited [yesterday](https://github.com/Mathilde-16/STOP_MS_data/issues/4#issue-2323658428):
![image](https://github.com/Mathilde-16/STOP_MS_data/assets/2482071/a6fe8e69-5922-4036-b27c-af32b15e5c80)

please make sure to test the link before posting-- thank you

**Comment by Mathilde-16** [comment]
https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh

**Comment by Mathilde-16** [comment]
https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh

**Comment by Mathilde-16** [comment]
The link below works well in my computer when I click on it or when I copy/paste it into a search engine. However, I don't know if it's going to work for you because when I copy/paste the link I wrote on the first message of this issue #4, it's work well too.

https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh

Hoping it's going to work for you

**Comment by jcohenadad** [comment]
yes, working well now, but in the future it is a good idea to avoid non alphanumerical ASCII characters like "&" which are interpreted in URLs as "%26" and depending on the OS/browser could cause issues

**Comment by jcohenadad** [comment]
I've commented the code via recent issues #7 #8 #9 #10

**Comment by Mathilde-16** [comment]
> yes, working well now, but in the future it is a good idea to avoid non alphanumerical ASCII characters like "&" which are interpreted in URLs as "%26" and depending on the OS/browser could cause issues

Okay, my apologies for this confusion.


> I've commented the code via recent issues https://github.com/Mathilde-16/STOP_MS_data/issues/7 https://github.com/Mathilde-16/STOP_MS_data/issues/8 https://github.com/Mathilde-16/STOP_MS_data/issues/9 https://github.com/Mathilde-16/STOP_MS_data/issues/10

Thank you for your help !

**Comment by jcohenadad** [comment]
will open a new issue in https://github.com/sct-pipeline/STOP-MS-data/issues to follow-up on recent processing results
