### ISSUE TITLE
Data processing progress : contrast-agnostic-segmentation and vertebral labeling

### ISSUE THREAD

**Issue by Mathilde-16** [Mathilde-16/STOP_MS_data#5]
Could you tell me what do you think about this script please ? 
[https://github.com/Mathilde-16/STOP_MS_data/blob/c1a80edec06823005e9c3bd31b535f213eb1bded/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh](url)

**Comment by jcohenadad** [comment]
same issue as https://github.com/Mathilde-16/STOP_MS_data/issues/4#issuecomment-2137849626

**Comment by Mathilde-16** [comment]
https://github.com/Mathilde-16/STOP_MS_data/blob/8240dfd021f558435050e73553de778ab5b0737b/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh 

Does the link above works for you ?

**Comment by jcohenadad** [comment]
yes it does, but isn't [this script](https://github.com/Mathilde-16/STOP_MS_data/blob/8240dfd021f558435050e73553de778ab5b0737b/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh) a somewhat duplicate of [this other script](https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh), on which i've already made comments? https://github.com/Mathilde-16/STOP_MS_data/issues/4#issuecomment-2142707197

This is all very confusing... I'm not sure what script is for what...

**Comment by Mathilde-16** [comment]
My explanations correspond to [this comment](https://github.com/Mathilde-16/STOP_MS_data/issues/7#issuecomment-2144529941) in issue #7

**Comment by jcohenadad** [comment]
I suggest to close this issue until the code duplication is solved-- then I will be able to give proper feedback on the codebase and methods comparison
