### ISSUE TITLE
Unclear what the 'template' file is

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#9]
https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L73

is this the PAM50 template? if so, this is not the typical way of registering to the PAM50 template (instead, use `sct_register_to_template`)

**Comment by Mathilde-16** [comment]
Thank you for your help, indeed I would like to use the PAM50 template. So I edited my script as follows : 
https://github.com/Mathilde-16/STOP_MS_data/blob/cf9ac61bb15fafd56dfaa5ecc9229c5d097c5b37/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L82-L86

Can I use this template in my script for the contrast agnostic model too ?

And I'm wondering if I need to use the PAM50 template knowing that one of our goals will be to compute CSA ? Indeed, I was doing some research on the SCT forum and I saw the following comment _"Do you really need to register to the PAM50 if your goal is to quantify lesions and CSA?"_  
Here is the link to the topic where I found this comment (this comment is in the last post of the discussion) : [https://forum.spinalcordmri.org/t/pam50-template-registration-for-highly-anisotropic-axial-scans/1117](url)

**Comment by jcohenadad** [comment]
> Can I use this template in my script for the contrast agnostic model too ?

yes-- the use of the PAM50 is agnostic to the segmentation method

**Comment by jcohenadad** [comment]
> And I'm wondering if I need to use the PAM50 template knowing that one of our goals will be to compute CSA ?

well, it depends what other goals are included in the "our goals". For CSA computation, registration to PAM50 is not required (see SCT course/tutorial)

**Comment by Mathilde-16** [comment]
> well, it depends what other goals are included in the "our goals"

(I have to ask a question to my team about it and I'll get back to you right away)

**Comment by Mathilde-16** [comment]
Our main goal is to compute CSA between C2-C3, but we would also like to compute the following morphometric measures using the **sct_process_segmentation** command : AP diameter, transverse diameter, solidity, compression ratio and eccentricity.

Moreover, I modified the [script](https://github.com/Mathilde-16/STOP_MS_data/commit/3fd27b79f4b2514b9d8b9e212a32d3abdde4d90c) and removed the sct_label_utils and the sct_register_to_template commands. Indeed, we would like to use the PAM50 template thanks to the **"-normalize-PAM50" flag**, as below :

https://github.com/Mathilde-16/STOP_MS_data/blob/5a820c9f28c9f10e817adc326258bbfecb65296a/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L82-L83
